# Generated by Django 3.1.4 on 2020-12-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('clases', '0002_auto_20201206_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='id_asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.asistencia'),
        ),
    ]
