# Generated by Django 3.1.4 on 2020-12-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('clases', '0003_clases_id_asistencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases',
            new_name='Clase',
        ),
    ]
