# Generated by Django 3.1.4 on 2020-12-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_remove_clase_id_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='clases',
        ),
    ]
